baseURL = '/'
languageCode = 'en-us'
title = 'Bloggraph Example Website'
theme = 'bloggraph'

[markup.goldmark.renderer]
    unsafe = true

[params.author]
    name = "Bar Foo"
    github = "desmondlzy/bloggraph"
    linkedin = ""
    email = ""

[menu]
[[menu.main]]
    name = "Home"
    url = '/'
    weight = 1
[[menu.main]]
    name = "Publications"
    url = '/publications'
    weight = 2